name: Build
on: [push, pull_request]

jobs:
  Build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    - name: Restore packages
      run: msbuild WindowsGSM.sln /t:restore
    - name: Build with MSBuild
      run: msbuild WindowsGSM.sln
